# Generated by Django 5.2.7 on 2025-10-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_to_go', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
