# Generated by Django 5.2.7 on 2025-10-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_to_go', '0002_place_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
            preserve_default=False,
        ),
    ]
