# Generated by Django 5.2.7 on 2025-10-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_to_go', '0003_place_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='menu',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
