# Generated by Django 5.2.7 on 2025-10-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_to_go', '0004_place_menu_place_site_alter_place_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
