# Generated by Django 5.2.7 on 2025-11-04 15:49

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_to_go', '0006_alter_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/places/', location='/home/das1/Projects_linux/Organisasion_project/places_to_go/static/places'), upload_to=''),
        ),
    ]
